alias: Notify Reuben of Jules Bug Fix
description: "Send notification when a Jules Bug Fix PR is created"
trigger:
  - platform: state
    entity_id: sensor.jules_session_status # This is hypothetical, assuming you have a sensor tracking sessions
    to: "completed"
condition: []
action:
  - service: notify.reuben_devices
    data:
      title: "TeslaCam Bug Fix"
      message: "Jules has created a new PR to fix a bug in TeslaCamPlayer."
mode: single
